#ifndef HASHLOG_BLOB_H
#define HASHLOG_BLOB_H

#include <hashlog/core/object.h>

/**
 * @brief Creates a new blob.
 * 
 * @param hex Output buffer to store the hash generated by the blob.
 */
int create_blob(char* text, size_t size, char hex[HASH_HEX_SIZE]);

#endif