#ifndef HASHLOG_COMMIT_H
#define HASHLOG_COMMIT_H

#include <string.h>

#include <hashlog/core/object.h>
#include <hashlog/core/config.h>

#define MAX_SIZE_COMMIT 4096

typedef struct {
    /** blob hash associated with commit */
    char blob[HASH_HEX_SIZE];
    /** parent hash associated with commit */
    char parent[HASH_HEX_SIZE];
    char author[128];
    char timestamp[DATETIME_SIZE];
} commit_info_t;

/**
 * @brief Creates a new commit.
 * 
 * @param hex Output buffer to store the hash generated by the commit.
 */
int create_commit(
    const char* blob_hex,
    const char* parent_hex,
    const char* author,
    char hex[HASH_HEX_SIZE]
);

/**
 * @brief Analyzes the content of a commit and populates the output structure.
 * 
 * @param content Raw content of the commit to be analyzed.
 * @param out A pointer to the `commit_info_t` structure where the data will be stored.
 */
void parse_commit(char* content, commit_info_t* out);

#endif