#ifndef HASHLOG_THREAD_H
#define HASHLOG_THREAD_H

#include <string.h>

#include <hashlog/core/object.h>
#include <hashlog/core/config.h>

typedef struct {
    /** head commit associated with the thread */
    char commit[HASH_HEX_SIZE];
} thread_info_t;

/**
 * @brief Creates a new thread based on an existing commit.
 * 
 * @param commit_hex Pointer to the hash of the reference commit.
 * @param hex Output buffer to store the hash generated by the thread.
 */
int create_thread(
    const char* commit_hex,
    char hex[HASH_HEX_SIZE]
);

/**
 * @brief Analyzes the content of a thread and populates the output structure.
 * 
 * @param content Raw content of the thread to be analyzed.
 * @param out A pointer to the `thread_info_t` structure where the data will be stored.
 */
void parse_thread(char* content, thread_info_t* out);

#endif